### ISSUE TITLE
config template leads to memory error.

### ISSUE THREAD

**Issue by pogden** [sudharsh/cloudcraft#1]
The config template uses a t1.micro instance with 615 MB of memory, and a max JVM heap size of 1GB. This can cause the JVM to try to expand its heap beyond the physical memory of the machine, crashing the server with chance of map corruption.

**Comment by sudharsh** [comment]
@pogden Thanks for bringing this up.

**Comment by pogden** [comment]
No problem, thanks for fixing it so fast.
